### ISSUE TITLE
Асинхронное подключение и инициализация компоненты

### ISSUE THREAD

**Issue by LevkinSergey** [cpr1c/RegEx1C_cfe#1]

**Comment by zeegin** [comment]
https://github.com/1c-syntax/ssl_3_1/blob/master/src/cf/CommonModules/%D0%9E%D0%B1%D1%89%D0%B5%D0%B3%D0%BE%D0%9D%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82/Ext/Module.bsl#L970

**Comment by LevkinSergey** [comment]
> https://github.com/1c-syntax/ssl_3_1/blob/master/src/cf/CommonModules/%D0%9E%D0%B1%D1%89%D0%B5%D0%B3%D0%BE%D0%9D%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82/Ext/Module.bsl#L970

Спасибо. то что нужно
